[2024-05-03T20:55:46.821-0300] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: a_primeira_DAG_v1.hello scheduled__2023-12-07T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
