[2024-05-06T18:33:49.972-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T18:33:49.999-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Hook_dag.task1 manual__2024-05-06T21:33:46.281592+00:00 [queued]>
[2024-05-06T18:33:50.015-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Hook_dag.task1 manual__2024-05-06T21:33:46.281592+00:00 [queued]>
[2024-05-06T18:33:50.015-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-06T18:33:50.053-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): task1> on 2024-05-06 21:33:46.281592+00:00
[2024-05-06T18:33:50.057-0300] {standard_task_runner.py:63} INFO - Started process 3726 to run task
[2024-05-06T18:33:50.060-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Hook_dag', 'task1', 'manual__2024-05-06T21:33:46.281592+00:00', '--job-id', '1152', '--raw', '--subdir', 'DAGS_FOLDER/hook_dag.py', '--cfg-path', '/tmp/tmp5liju7a9']
[2024-05-06T18:33:50.061-0300] {standard_task_runner.py:91} INFO - Job 1152: Subtask task1
[2024-05-06T18:33:50.136-0300] {task_command.py:426} INFO - Running <TaskInstance: Hook_dag.task1 manual__2024-05-06T21:33:46.281592+00:00 [running]> on host PC-Tilto.
[2024-05-06T18:33:50.425-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Hook_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T21:33:46.281592+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T21:33:46.281592+00:00'
[2024-05-06T18:33:50.425-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T18:33:50.435-0300] {postgres.py:175} INFO - Running copy expert: COPY (SELECT * FROM characters) TO stdout WITH CSV HEADER, filename: /mnt/c/Users/Tilto/Desktop/Work/Airflow/data/characters.csv
[2024-05-06T18:33:50.452-0300] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-06T18:33:51.490-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T18:33:51.490-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/hook_dag.py", line 11, in read_data
    pghook.copy_expert(
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/postgres/hooks/postgres.py", line 180, in copy_expert
    with open(filename, "r+") as file, closing(self.get_conn()) as conn, closing(conn.cursor()) as cur:
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known

[2024-05-06T18:33:51.504-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=Hook_dag, task_id=task1, execution_date=20240506T213346, start_date=20240506T213350, end_date=20240506T213351
[2024-05-06T18:33:51.540-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 1152 for task task1 (could not translate host name "postgres" to address: Name or service not known
; 3726)
[2024-05-06T18:33:51.556-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-06T18:33:51.582-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-06T18:33:51.679-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
