[2024-05-08T00:09:35.333-0300] {processor.py:161} INFO - Started process (PID=10948) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:09:35.334-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T00:09:35.336-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:09:35.335-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:09:35.368-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:09:35.363-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T00:09:35.371-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:09:35.406-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.078 seconds
[2024-05-08T00:10:06.706-0300] {processor.py:161} INFO - Started process (PID=11093) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:10:06.707-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T00:10:06.708-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:10:06.708-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:10:06.729-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:10:06.725-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T00:10:06.731-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:10:06.766-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.065 seconds
[2024-05-08T00:10:26.150-0300] {processor.py:161} INFO - Started process (PID=11189) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:10:26.151-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T00:10:26.152-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:10:26.152-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:10:26.185-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:10:26.181-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T00:10:26.187-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:10:26.220-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.075 seconds
[2024-05-08T00:10:56.930-0300] {processor.py:161} INFO - Started process (PID=11331) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:10:56.931-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T00:10:56.933-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:10:56.932-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:10:56.954-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:10:56.950-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T00:10:56.956-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:10:56.992-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.069 seconds
[2024-05-08T00:11:28.170-0300] {processor.py:161} INFO - Started process (PID=11475) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:11:28.171-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T00:11:28.173-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:11:28.173-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:11:28.195-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:11:28.190-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T00:11:28.197-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:11:28.286-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.120 seconds
[2024-05-08T00:11:59.203-0300] {processor.py:161} INFO - Started process (PID=11618) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:11:59.204-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T00:11:59.205-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:11:59.205-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:11:59.227-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:11:59.222-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T00:11:59.229-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:11:59.264-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.066 seconds
[2024-05-08T00:12:30.284-0300] {processor.py:161} INFO - Started process (PID=11762) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:12:30.285-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T00:12:30.286-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:12:30.286-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:12:30.307-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:12:30.302-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T00:12:30.309-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:12:30.341-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.061 seconds
[2024-05-08T00:13:01.238-0300] {processor.py:161} INFO - Started process (PID=11904) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:13:01.239-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T00:13:01.240-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:13:01.240-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:13:01.260-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:13:01.256-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T00:13:01.262-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:13:01.295-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.062 seconds
[2024-05-08T00:13:12.680-0300] {processor.py:161} INFO - Started process (PID=11951) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:13:12.683-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T00:13:12.685-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:13:12.685-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:13:12.732-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:13:12.726-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T00:13:12.735-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:13:12.847-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.173 seconds
[2024-05-08T00:13:43.482-0300] {processor.py:161} INFO - Started process (PID=12094) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:13:43.483-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T00:13:43.484-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:13:43.484-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:13:43.504-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:13:43.499-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T00:13:43.506-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:13:43.539-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.061 seconds
[2024-05-08T00:14:02.189-0300] {processor.py:161} INFO - Started process (PID=12192) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:14:02.191-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T00:14:02.193-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:14:02.193-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:14:02.284-0300] {logging_mixin.py:188} INFO - [2024-05-08T00:14:02.273-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T00:14:02.294-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T00:14:02.456-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.281 seconds
[2024-05-08T16:18:00.716-0300] {processor.py:161} INFO - Started process (PID=2675) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:18:00.717-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:18:00.719-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:18:00.719-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:18:00.758-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:18:00.753-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:18:00.761-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:18:00.800-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.089 seconds
[2024-05-08T16:18:31.790-0300] {processor.py:161} INFO - Started process (PID=2829) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:18:31.791-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:18:31.792-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:18:31.792-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:18:31.813-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:18:31.808-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:18:31.814-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:18:31.847-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.062 seconds
[2024-05-08T16:18:49.721-0300] {processor.py:161} INFO - Started process (PID=2967) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:18:49.722-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:18:49.726-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:18:49.724-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:18:49.770-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:18:49.765-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:18:49.772-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:18:49.810-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.095 seconds
[2024-05-08T16:19:19.954-0300] {processor.py:161} INFO - Started process (PID=3195) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:19:19.955-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:19:19.957-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:19:19.957-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:19:19.978-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:19:19.974-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:19:19.980-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:19:20.021-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.071 seconds
[2024-05-08T16:19:47.928-0300] {processor.py:161} INFO - Started process (PID=3329) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:19:47.929-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:19:47.933-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:19:47.932-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:19:47.985-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:19:47.979-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:19:47.988-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:19:48.084-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.164 seconds
[2024-05-08T16:20:18.232-0300] {processor.py:161} INFO - Started process (PID=3477) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:20:18.232-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:20:18.234-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:20:18.234-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:20:18.255-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:20:18.250-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:20:18.256-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:20:18.290-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.064 seconds
[2024-05-08T16:20:43.170-0300] {processor.py:161} INFO - Started process (PID=3633) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:20:43.172-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:20:43.173-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:20:43.173-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:20:43.214-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:20:43.209-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:20:43.215-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:20:43.256-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.091 seconds
[2024-05-08T16:21:14.445-0300] {processor.py:161} INFO - Started process (PID=3792) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:21:14.446-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:21:14.448-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:21:14.447-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:21:14.464-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:21:14.461-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:21:14.466-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:21:14.495-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.055 seconds
[2024-05-08T16:21:45.174-0300] {processor.py:161} INFO - Started process (PID=3938) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:21:45.175-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:21:45.176-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:21:45.176-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:21:45.194-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:21:45.190-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:21:45.196-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:21:45.226-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.057 seconds
[2024-05-08T16:22:39.722-0300] {processor.py:161} INFO - Started process (PID=4298) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:22:39.723-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:22:39.725-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:22:39.725-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:22:39.766-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:22:39.759-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:22:39.768-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:22:39.808-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.091 seconds
[2024-05-08T16:23:16.749-0300] {processor.py:161} INFO - Started process (PID=4485) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:23:16.750-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:23:16.751-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:23:16.751-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:23:16.772-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:23:16.768-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:23:16.774-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:23:16.812-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.068 seconds
[2024-05-08T16:23:47.561-0300] {processor.py:161} INFO - Started process (PID=4627) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:23:47.562-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:23:47.564-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:23:47.563-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:23:47.591-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:23:47.585-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:23:47.594-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:23:47.633-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.078 seconds
[2024-05-08T16:24:18.586-0300] {processor.py:161} INFO - Started process (PID=4775) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:24:18.587-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:24:18.589-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:24:18.589-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:24:18.613-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:24:18.607-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:24:18.615-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:24:18.653-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.074 seconds
[2024-05-08T16:24:49.631-0300] {processor.py:161} INFO - Started process (PID=4920) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:24:49.632-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:24:49.634-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:24:49.634-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:24:49.654-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:24:49.650-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:24:49.656-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:24:49.693-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.066 seconds
[2024-05-08T16:25:20.805-0300] {processor.py:161} INFO - Started process (PID=5064) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:25:20.806-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:25:20.808-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:25:20.807-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:25:20.833-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:25:20.828-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:25:20.835-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:25:20.872-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.072 seconds
[2024-05-08T16:25:51.041-0300] {processor.py:161} INFO - Started process (PID=5208) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:25:51.042-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:25:51.043-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:25:51.043-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:25:51.065-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:25:51.061-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:25:51.067-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:25:51.112-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.075 seconds
[2024-05-08T16:26:21.731-0300] {processor.py:161} INFO - Started process (PID=5351) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:26:21.732-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:26:21.734-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:26:21.733-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:26:21.755-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:26:21.749-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:26:21.757-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:26:21.789-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.062 seconds
[2024-05-08T16:26:52.819-0300] {processor.py:161} INFO - Started process (PID=5495) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:26:52.820-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:26:52.822-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:26:52.822-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:26:52.842-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:26:52.838-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:26:52.844-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:26:52.879-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.064 seconds
[2024-05-08T16:27:24.093-0300] {processor.py:161} INFO - Started process (PID=5644) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:27:24.094-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:27:24.096-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:27:24.095-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:27:24.134-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:27:24.128-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:27:24.136-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:27:24.174-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.087 seconds
[2024-05-08T16:27:55.401-0300] {processor.py:161} INFO - Started process (PID=5792) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:27:55.402-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:27:55.404-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:27:55.403-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:27:55.432-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:27:55.426-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:27:55.435-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:27:55.477-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.082 seconds
[2024-05-08T16:28:26.374-0300] {processor.py:161} INFO - Started process (PID=5938) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:28:26.375-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:28:26.378-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:28:26.377-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:28:26.399-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:28:26.394-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:28:26.401-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:28:26.439-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.072 seconds
[2024-05-08T16:28:57.171-0300] {processor.py:161} INFO - Started process (PID=6081) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:28:57.172-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:28:57.173-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:28:57.173-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:28:57.195-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:28:57.190-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:28:57.197-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:28:57.234-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.067 seconds
[2024-05-08T16:29:28.195-0300] {processor.py:161} INFO - Started process (PID=6225) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:29:28.196-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:29:28.198-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:29:28.197-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:29:28.225-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:29:28.219-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:29:28.229-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:29:28.278-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.092 seconds
[2024-05-08T16:29:59.387-0300] {processor.py:161} INFO - Started process (PID=6378) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:29:59.388-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:29:59.389-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:29:59.389-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:29:59.413-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:29:59.407-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:29:59.416-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:29:59.502-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.119 seconds
[2024-05-08T16:30:30.298-0300] {processor.py:161} INFO - Started process (PID=6528) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:30:30.299-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:30:30.301-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:30:30.301-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:30:30.325-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:30:30.319-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:30:30.327-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:30:30.398-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.105 seconds
[2024-05-08T16:31:01.164-0300] {processor.py:161} INFO - Started process (PID=6671) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:31:01.165-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:31:01.166-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:31:01.166-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:31:01.187-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:31:01.182-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:31:01.189-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:31:01.225-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.066 seconds
[2024-05-08T16:31:32.111-0300] {processor.py:161} INFO - Started process (PID=6815) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:31:32.112-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:31:32.114-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:31:32.113-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:31:32.134-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:31:32.130-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:31:32.136-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:31:32.171-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.065 seconds
[2024-05-08T16:32:03.134-0300] {processor.py:161} INFO - Started process (PID=6959) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:32:03.135-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:32:03.137-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:32:03.137-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:32:03.159-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:32:03.154-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:32:03.161-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:32:03.197-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.067 seconds
[2024-05-08T16:32:34.076-0300] {processor.py:161} INFO - Started process (PID=7103) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:32:34.077-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:32:34.079-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:32:34.079-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:32:34.103-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:32:34.097-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:32:34.105-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:32:34.143-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.071 seconds
[2024-05-08T16:33:04.367-0300] {processor.py:161} INFO - Started process (PID=7244) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:33:04.368-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:33:04.369-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:33:04.369-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:33:04.386-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:33:04.382-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:33:04.388-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:33:04.485-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.123 seconds
[2024-05-08T16:33:35.448-0300] {processor.py:161} INFO - Started process (PID=7388) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:33:35.449-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:33:35.451-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:33:35.451-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:33:35.469-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:33:35.465-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:33:35.470-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:33:35.507-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.066 seconds
[2024-05-08T16:34:06.616-0300] {processor.py:161} INFO - Started process (PID=7533) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:34:06.617-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:34:06.620-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:34:06.619-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:34:06.647-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:34:06.641-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:34:06.650-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:34:06.696-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.086 seconds
[2024-05-08T16:34:37.776-0300] {processor.py:161} INFO - Started process (PID=7677) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:34:37.777-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:34:37.779-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:34:37.778-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:34:37.797-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:34:37.791-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:34:37.798-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:34:37.831-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.059 seconds
[2024-05-08T16:35:08.056-0300] {processor.py:161} INFO - Started process (PID=7819) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:35:08.057-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:35:08.060-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:35:08.059-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:35:08.086-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:35:08.080-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:35:08.088-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:35:08.125-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.075 seconds
[2024-05-08T16:35:39.177-0300] {processor.py:161} INFO - Started process (PID=7964) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:35:39.178-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:35:39.179-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:35:39.179-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:35:39.197-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:35:39.193-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:35:39.200-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:35:39.236-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.065 seconds
[2024-05-08T16:36:10.341-0300] {processor.py:161} INFO - Started process (PID=8108) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:36:10.342-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:36:10.343-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:36:10.343-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:36:10.369-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:36:10.363-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:36:10.371-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:36:10.412-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.078 seconds
[2024-05-08T16:36:41.171-0300] {processor.py:161} INFO - Started process (PID=8252) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:36:41.172-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:36:41.174-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:36:41.174-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:36:41.189-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:36:41.186-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:36:41.191-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:36:41.220-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.053 seconds
[2024-05-08T16:37:11.999-0300] {processor.py:161} INFO - Started process (PID=8395) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:37:12.000-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:37:12.001-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:37:12.001-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:37:12.019-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:37:12.015-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:37:12.021-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:37:12.050-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.055 seconds
[2024-05-08T16:37:42.394-0300] {processor.py:161} INFO - Started process (PID=8537) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:37:42.395-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:37:42.397-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:37:42.396-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:37:42.419-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:37:42.414-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:37:42.421-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:37:42.457-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.069 seconds
[2024-05-08T16:38:13.052-0300] {processor.py:161} INFO - Started process (PID=8679) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:38:13.053-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:38:13.055-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:38:13.054-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:38:13.072-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:38:13.068-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:38:13.073-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:38:13.106-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.059 seconds
[2024-05-08T16:38:44.063-0300] {processor.py:161} INFO - Started process (PID=8993) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:38:44.075-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:38:44.104-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:38:44.103-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:38:44.169-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:38:44.157-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:38:44.173-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:38:44.266-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.213 seconds
[2024-05-08T16:39:15.118-0300] {processor.py:161} INFO - Started process (PID=9138) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:39:15.122-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T16:39:15.125-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:39:15.124-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:39:15.162-0300] {logging_mixin.py:188} INFO - [2024-05-08T16:39:15.155-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T16:39:15.165-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T16:39:15.226-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.118 seconds
[2024-05-08T17:55:44.101-0300] {processor.py:161} INFO - Started process (PID=27279) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T17:55:44.101-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py for tasks to queue
[2024-05-08T17:55:44.105-0300] {logging_mixin.py:188} INFO - [2024-05-08T17:55:44.105-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T17:55:44.157-0300] {logging_mixin.py:188} INFO - [2024-05-08T17:55:44.150-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py", line 6, in <module>
    from airflow.operators.postgres_hook import PostgresHook
ModuleNotFoundError: No module named 'airflow.operators.postgres_hook'
[2024-05-08T17:55:44.160-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py
[2024-05-08T17:55:44.312-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/atividade01_dag.py took 0.220 seconds
