[2024-05-01T17:50:14.940-0300] {processor.py:161} INFO - Started process (PID=1898) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:50:14.941-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:50:14.943-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:50:14.942-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:50:14.964-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:50:14.963-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:50:14.965-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:50:15.003-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.067 seconds
[2024-05-01T17:50:46.067-0300] {processor.py:161} INFO - Started process (PID=2037) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:50:46.068-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:50:46.070-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:50:46.070-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:50:46.090-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:50:46.089-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:50:46.091-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:50:46.125-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.062 seconds
[2024-05-01T17:51:16.966-0300] {processor.py:161} INFO - Started process (PID=2168) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:51:16.967-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:51:16.969-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:51:16.969-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:51:16.990-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:51:16.989-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:51:16.991-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:51:17.028-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.069 seconds
[2024-05-01T17:51:47.796-0300] {processor.py:161} INFO - Started process (PID=2303) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:51:47.797-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:51:47.798-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:51:47.798-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:51:47.818-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:51:47.817-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:51:47.819-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:51:47.853-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.061 seconds
[2024-05-01T17:52:18.343-0300] {processor.py:161} INFO - Started process (PID=2430) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:52:18.345-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:52:18.347-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:52:18.347-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:52:18.385-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:52:18.384-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:52:18.386-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:52:18.453-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.117 seconds
[2024-05-01T17:52:48.590-0300] {processor.py:161} INFO - Started process (PID=2558) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:52:48.591-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:52:48.592-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:52:48.591-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:52:48.611-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:52:48.611-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:52:48.612-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:52:48.646-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.060 seconds
[2024-05-01T17:53:19.208-0300] {processor.py:161} INFO - Started process (PID=2711) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:53:19.209-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:53:19.209-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:53:19.209-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:53:19.229-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:53:19.228-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:53:19.229-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:53:19.262-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.059 seconds
[2024-05-01T17:53:50.053-0300] {processor.py:161} INFO - Started process (PID=2843) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:53:50.054-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:53:50.055-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:53:50.055-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:53:50.079-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:53:50.079-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:53:50.080-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:53:50.125-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.078 seconds
[2024-05-01T17:54:20.860-0300] {processor.py:161} INFO - Started process (PID=2972) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:54:20.861-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:54:20.862-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:54:20.862-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:54:20.877-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:54:20.876-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:54:20.877-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:54:20.911-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.055 seconds
[2024-05-01T17:54:51.626-0300] {processor.py:161} INFO - Started process (PID=3178) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:54:51.627-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:54:51.628-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:54:51.628-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:54:51.643-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:54:51.643-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:54:51.644-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:54:51.681-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.059 seconds
[2024-05-01T17:55:22.345-0300] {processor.py:161} INFO - Started process (PID=3305) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:55:22.346-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:55:22.347-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:55:22.347-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:55:22.359-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:55:22.358-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:55:22.360-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:55:22.393-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.052 seconds
[2024-05-01T17:55:53.131-0300] {processor.py:161} INFO - Started process (PID=3434) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:55:53.132-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:55:53.133-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:55:53.132-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:55:53.148-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:55:53.148-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:55:53.149-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:55:53.182-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.056 seconds
[2024-05-01T17:56:23.664-0300] {processor.py:161} INFO - Started process (PID=3563) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:56:23.666-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:56:23.667-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:56:23.666-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:56:23.681-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:56:23.680-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:56:23.682-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:56:23.722-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.063 seconds
[2024-05-01T17:56:54.131-0300] {processor.py:161} INFO - Started process (PID=3689) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:56:54.132-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:56:54.133-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:56:54.133-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:56:54.145-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:56:54.144-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:56:54.145-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:56:54.177-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.052 seconds
[2024-05-01T17:57:24.547-0300] {processor.py:161} INFO - Started process (PID=3817) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:57:24.548-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:57:24.549-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:57:24.548-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:57:24.561-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:57:24.560-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:57:24.561-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:57:24.593-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.052 seconds
[2024-05-01T17:57:56.292-0300] {processor.py:161} INFO - Started process (PID=3952) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:57:56.293-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:57:56.294-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:57:56.294-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:57:56.306-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:57:56.305-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:57:56.307-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:57:56.340-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.053 seconds
[2024-05-01T17:58:26.830-0300] {processor.py:161} INFO - Started process (PID=4082) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:58:26.831-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:58:26.832-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:58:26.832-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:58:26.847-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:58:26.847-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:58:26.848-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:58:26.882-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.057 seconds
[2024-05-01T17:59:03.328-0300] {processor.py:161} INFO - Started process (PID=4238) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:59:03.329-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:59:03.330-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:59:03.330-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:59:03.346-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:59:03.345-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:59:03.346-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:59:04.176-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.853 seconds
[2024-05-01T17:59:34.439-0300] {processor.py:161} INFO - Started process (PID=4367) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:59:34.440-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T17:59:34.441-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:59:34.440-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:59:34.455-0300] {logging_mixin.py:188} INFO - [2024-05-01T17:59:34.454-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T17:59:34.455-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T17:59:34.491-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.056 seconds
[2024-05-01T18:00:05.220-0300] {processor.py:161} INFO - Started process (PID=4496) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:00:05.221-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:00:05.222-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:00:05.221-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:00:05.235-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:00:05.235-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:00:05.236-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:00:05.269-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.054 seconds
[2024-05-01T18:00:36.124-0300] {processor.py:161} INFO - Started process (PID=4626) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:00:36.125-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:00:36.126-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:00:36.126-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:00:36.143-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:00:36.143-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:00:36.144-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:00:36.184-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.065 seconds
[2024-05-01T18:01:24.206-0300] {processor.py:161} INFO - Started process (PID=4853) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:01:24.207-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:01:24.209-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:01:24.209-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:01:24.225-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:01:24.224-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:01:24.225-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:01:24.263-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.063 seconds
[2024-05-01T18:01:55.193-0300] {processor.py:161} INFO - Started process (PID=4980) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:01:55.194-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:01:55.195-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:01:55.195-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:01:55.211-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:01:55.210-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:01:55.212-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:01:55.247-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.058 seconds
[2024-05-01T18:02:25.939-0300] {processor.py:161} INFO - Started process (PID=5106) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:02:25.940-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:02:25.941-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:02:25.941-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:02:25.957-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:02:25.956-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:02:25.957-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:02:25.993-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.059 seconds
[2024-05-01T18:02:56.648-0300] {processor.py:161} INFO - Started process (PID=5231) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:02:56.649-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:02:56.651-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:02:56.651-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:02:56.667-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:02:56.666-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:02:56.667-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:02:56.704-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.061 seconds
[2024-05-01T18:03:28.726-0300] {processor.py:161} INFO - Started process (PID=5366) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:03:28.728-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:03:28.737-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:03:28.737-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:03:28.765-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:03:28.764-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:03:28.766-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:03:28.934-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.216 seconds
[2024-05-01T18:03:59.397-0300] {processor.py:161} INFO - Started process (PID=5494) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:03:59.398-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:03:59.400-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:03:59.400-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:03:59.414-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:03:59.413-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:03:59.414-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:03:59.447-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.054 seconds
[2024-05-01T18:04:30.037-0300] {processor.py:161} INFO - Started process (PID=5620) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:04:30.038-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:04:30.039-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:04:30.039-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:04:30.055-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:04:30.054-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:04:30.055-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:04:30.091-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.058 seconds
[2024-05-01T18:05:00.636-0300] {processor.py:161} INFO - Started process (PID=5745) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:05:00.637-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:05:00.638-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:05:00.638-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:05:00.652-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:05:00.652-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:05:00.653-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:05:00.690-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.059 seconds
[2024-05-01T18:05:31.306-0300] {processor.py:161} INFO - Started process (PID=5871) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:05:31.307-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:05:31.309-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:05:31.308-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:05:31.323-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:05:31.322-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:05:31.323-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:05:31.357-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.055 seconds
[2024-05-01T18:06:01.709-0300] {processor.py:161} INFO - Started process (PID=5999) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:06:01.710-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:06:01.711-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:06:01.711-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:06:01.726-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:06:01.726-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:06:01.727-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:06:01.759-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.054 seconds
[2024-05-01T18:06:32.120-0300] {processor.py:161} INFO - Started process (PID=6123) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:06:32.121-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:06:32.123-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:06:32.123-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:06:32.137-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:06:32.137-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:06:32.138-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:06:32.171-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.055 seconds
[2024-05-01T18:07:02.519-0300] {processor.py:161} INFO - Started process (PID=6248) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:07:02.520-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:07:02.521-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:07:02.521-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:07:02.536-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:07:02.535-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:07:02.536-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:07:02.570-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.056 seconds
[2024-05-01T18:07:33.967-0300] {processor.py:161} INFO - Started process (PID=6377) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:07:33.968-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:07:33.969-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:07:33.969-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:07:33.984-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:07:33.983-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:07:33.985-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:07:34.018-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.056 seconds
[2024-05-01T18:08:04.859-0300] {processor.py:161} INFO - Started process (PID=6507) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:08:04.860-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:08:04.861-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:08:04.861-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:08:04.875-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:08:04.875-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:08:04.876-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:08:04.908-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.054 seconds
[2024-05-01T18:08:35.561-0300] {processor.py:161} INFO - Started process (PID=6633) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:08:35.562-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:08:35.563-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:08:35.563-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:08:35.579-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:08:35.578-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:08:35.579-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:08:35.612-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.055 seconds
[2024-05-01T18:09:06.333-0300] {processor.py:161} INFO - Started process (PID=6759) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:09:06.334-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:09:06.336-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:09:06.335-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:09:06.350-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:09:06.349-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:09:06.350-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:09:06.385-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.056 seconds
[2024-05-01T18:09:36.982-0300] {processor.py:161} INFO - Started process (PID=6885) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:09:36.983-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:09:36.985-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:09:36.984-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:09:36.999-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:09:36.998-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:09:37.000-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:09:37.033-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.055 seconds
[2024-05-01T18:10:07.373-0300] {processor.py:161} INFO - Started process (PID=7012) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:10:07.374-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:10:07.376-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:10:07.375-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:10:07.389-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:10:07.389-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:10:07.390-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:10:07.423-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.054 seconds
[2024-05-01T18:10:37.685-0300] {processor.py:161} INFO - Started process (PID=7137) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:10:37.686-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:10:37.687-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:10:37.687-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:10:37.701-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:10:37.701-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:10:37.702-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:10:37.735-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.055 seconds
[2024-05-01T18:11:07.999-0300] {processor.py:161} INFO - Started process (PID=7261) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:11:07.999-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:11:08.001-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:11:08.000-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:11:08.015-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:11:08.014-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:11:08.015-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:11:08.047-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.053 seconds
[2024-05-01T18:11:38.380-0300] {processor.py:161} INFO - Started process (PID=7388) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:11:38.381-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:11:38.382-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:11:38.382-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:11:38.400-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:11:38.400-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:11:38.401-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:11:38.442-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.068 seconds
[2024-05-01T18:25:21.358-0300] {processor.py:161} INFO - Started process (PID=879) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:25:21.359-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:25:21.361-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:25:21.360-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:25:21.379-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:25:21.378-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:25:21.379-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:25:21.413-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.059 seconds
[2024-05-01T18:25:52.653-0300] {processor.py:161} INFO - Started process (PID=1014) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:25:52.654-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:25:52.656-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:25:52.655-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:25:52.677-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:25:52.677-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:25:52.678-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:25:52.711-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.063 seconds
[2024-05-01T18:26:23.532-0300] {processor.py:161} INFO - Started process (PID=1146) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:26:23.533-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:26:23.535-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:26:23.535-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:26:23.555-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:26:23.554-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:26:23.555-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:26:23.590-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.062 seconds
[2024-05-01T18:26:54.422-0300] {processor.py:161} INFO - Started process (PID=1277) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:26:54.423-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:26:54.425-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:26:54.424-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:26:54.441-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:26:54.440-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:26:54.442-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:26:54.477-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.059 seconds
[2024-05-01T18:27:25.252-0300] {processor.py:161} INFO - Started process (PID=1408) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:27:25.253-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:27:25.254-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:27:25.254-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:27:25.270-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:27:25.270-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:27:25.271-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:27:25.302-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.055 seconds
[2024-05-01T18:27:56.011-0300] {processor.py:161} INFO - Started process (PID=1540) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:27:56.012-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:27:56.013-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:27:56.013-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:27:56.030-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:27:56.029-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:27:56.030-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:27:56.062-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.056 seconds
[2024-05-01T18:28:26.691-0300] {processor.py:161} INFO - Started process (PID=1671) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:28:26.692-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:28:26.694-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:28:26.694-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:28:26.713-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:28:26.712-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:28:26.714-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:28:27.099-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.413 seconds
[2024-05-01T18:34:01.459-0300] {processor.py:161} INFO - Started process (PID=3110) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:34:01.460-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:34:01.461-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:34:01.461-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:34:01.481-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:34:01.480-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:34:01.481-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:34:01.517-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.062 seconds
[2024-05-01T18:34:32.679-0300] {processor.py:161} INFO - Started process (PID=3244) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:34:32.680-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:34:32.682-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:34:32.682-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:34:32.705-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:34:32.705-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:34:32.706-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:34:32.742-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.067 seconds
[2024-05-01T18:35:25.861-0300] {processor.py:161} INFO - Started process (PID=3515) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:35:25.862-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:35:25.864-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:35:25.863-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:35:25.883-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:35:25.883-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:35:25.884-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:35:25.917-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.060 seconds
[2024-05-01T18:35:59.668-0300] {processor.py:161} INFO - Started process (PID=3706) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:35:59.669-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:35:59.671-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:35:59.670-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:35:59.691-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:35:59.691-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:35:59.692-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:35:59.728-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.064 seconds
[2024-05-01T18:36:30.718-0300] {processor.py:161} INFO - Started process (PID=3890) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:36:30.719-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:36:30.720-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:36:30.720-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:36:30.738-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:36:30.737-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:36:30.738-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:36:30.771-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.058 seconds
[2024-05-01T18:37:01.548-0300] {processor.py:161} INFO - Started process (PID=4069) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:37:01.549-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:37:01.550-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:37:01.550-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:37:01.568-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:37:01.567-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:37:01.568-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:37:01.605-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.063 seconds
[2024-05-01T18:37:33.077-0300] {processor.py:161} INFO - Started process (PID=4250) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:37:33.079-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:37:33.081-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:37:33.080-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:37:33.102-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:37:33.101-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:37:33.103-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:37:33.144-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.074 seconds
[2024-05-01T18:38:04.023-0300] {processor.py:161} INFO - Started process (PID=4430) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:38:04.024-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:38:04.025-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:38:04.025-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:38:04.045-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:38:04.044-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:38:04.045-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:38:04.081-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.063 seconds
[2024-05-01T18:38:36.528-0300] {processor.py:161} INFO - Started process (PID=4620) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:38:36.529-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:38:36.530-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:38:36.530-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:38:36.550-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:38:36.550-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:38:36.551-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:38:36.586-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.062 seconds
[2024-05-01T18:39:08.736-0300] {processor.py:161} INFO - Started process (PID=4801) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:39:08.737-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:39:08.739-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:39:08.739-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:39:08.759-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:39:08.759-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:39:08.760-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:39:08.796-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.067 seconds
[2024-05-01T18:39:40.539-0300] {processor.py:161} INFO - Started process (PID=4984) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:39:40.540-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:39:40.541-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:39:40.541-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:39:40.557-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:39:40.556-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:39:40.558-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:39:40.592-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.058 seconds
[2024-05-01T18:40:11.468-0300] {processor.py:161} INFO - Started process (PID=5163) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:40:11.469-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:40:11.471-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:40:11.470-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:40:11.487-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:40:11.487-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:40:11.488-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:40:11.519-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.056 seconds
[2024-05-01T18:40:43.354-0300] {processor.py:161} INFO - Started process (PID=5349) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:40:43.354-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:40:43.356-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:40:43.356-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:40:43.376-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:40:43.375-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py", line 6
    AIRFLOW_HOME = 'C:\Users\Tilto\Desktop\Work\Airflow Aula'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-01T18:40:43.377-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:40:43.411-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.063 seconds
[2024-05-01T18:42:54.983-0300] {processor.py:161} INFO - Started process (PID=5921) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:42:54.984-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:42:54.985-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:42:54.985-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:42:55.003-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:42:55.016-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:42:55.016-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:42:55.031-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:42:55.030-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:42:55.101-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.122 seconds
[2024-05-01T18:43:25.668-0300] {processor.py:161} INFO - Started process (PID=6084) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:43:25.669-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:43:25.670-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:43:25.670-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:43:25.689-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:43:25.800-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:43:25.800-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:43:25.812-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:43:25.812-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:43:25.874-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.210 seconds
[2024-05-01T18:43:57.046-0300] {processor.py:161} INFO - Started process (PID=6215) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:43:57.047-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:43:57.048-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:43:57.048-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:43:57.065-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:43:57.094-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:43:57.093-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:43:57.108-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:43:57.108-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:43:57.174-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.133 seconds
[2024-05-01T18:44:27.273-0300] {processor.py:161} INFO - Started process (PID=6340) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:44:27.274-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:44:27.275-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:44:27.275-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:44:27.291-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:44:27.318-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:44:27.317-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:44:27.330-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:44:27.330-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:44:27.389-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.120 seconds
[2024-05-01T18:44:57.717-0300] {processor.py:161} INFO - Started process (PID=6466) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:44:57.718-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:44:57.720-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:44:57.720-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:44:57.737-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:44:57.764-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:44:57.764-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:44:57.777-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:44:57.777-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:44:57.837-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.124 seconds
[2024-05-01T18:45:28.144-0300] {processor.py:161} INFO - Started process (PID=6591) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:45:28.145-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:45:28.146-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:45:28.146-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:45:28.163-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:45:28.190-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:45:28.190-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:45:28.203-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:45:28.203-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:45:28.331-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.192 seconds
[2024-05-01T18:45:58.659-0300] {processor.py:161} INFO - Started process (PID=6716) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:45:58.660-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:45:58.662-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:45:58.661-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:45:58.678-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:45:58.703-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:45:58.703-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:45:58.716-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:45:58.716-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:45:58.777-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.122 seconds
[2024-05-01T18:46:31.016-0300] {processor.py:161} INFO - Started process (PID=6849) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:46:31.017-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:46:31.019-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:46:31.019-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:46:31.035-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:46:31.061-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:46:31.060-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:46:31.073-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:46:31.073-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:46:32.969-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 1.957 seconds
[2024-05-01T18:47:03.563-0300] {processor.py:161} INFO - Started process (PID=6985) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:47:03.564-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:47:03.565-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:47:03.565-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:47:03.582-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:47:03.608-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:47:03.607-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:47:03.620-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:47:03.620-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:47:03.703-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.144 seconds
[2024-05-01T18:47:34.193-0300] {processor.py:161} INFO - Started process (PID=7114) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:47:34.194-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:47:34.196-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:47:34.196-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:47:34.214-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:47:34.240-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:47:34.240-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:47:34.253-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:47:34.252-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:47:34.312-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.123 seconds
[2024-05-01T18:48:04.710-0300] {processor.py:161} INFO - Started process (PID=7239) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:48:04.711-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:48:04.712-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:48:04.712-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:48:04.729-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:48:04.756-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:48:04.756-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:48:04.769-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:48:04.768-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:48:04.829-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.123 seconds
[2024-05-01T18:48:35.277-0300] {processor.py:161} INFO - Started process (PID=7368) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:48:35.278-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:48:35.280-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:48:35.280-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:48:35.298-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:48:35.323-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:48:35.323-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:48:35.336-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:48:35.335-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:48:35.395-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.122 seconds
[2024-05-01T18:49:05.817-0300] {processor.py:161} INFO - Started process (PID=7494) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:49:05.818-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:49:05.820-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:49:05.820-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:49:05.836-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:49:05.862-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:49:05.861-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:49:05.874-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:49:05.873-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:49:05.932-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.119 seconds
[2024-05-01T18:49:36.484-0300] {processor.py:161} INFO - Started process (PID=7620) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:49:36.485-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:49:36.486-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:49:36.486-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:49:36.502-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:49:36.532-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:49:36.531-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:49:36.546-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:49:36.546-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:49:36.612-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.132 seconds
[2024-05-01T18:50:07.557-0300] {processor.py:161} INFO - Started process (PID=7748) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:50:07.558-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:50:07.559-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:50:07.559-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:50:07.579-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:50:07.607-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:50:07.606-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:50:07.619-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:50:07.619-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:50:07.685-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.133 seconds
[2024-05-01T18:50:38.087-0300] {processor.py:161} INFO - Started process (PID=7876) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:50:38.088-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:50:38.090-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:50:38.089-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:50:38.106-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:50:38.130-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:50:38.130-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:50:38.143-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:50:38.142-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:50:38.202-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.120 seconds
[2024-05-01T18:51:08.619-0300] {processor.py:161} INFO - Started process (PID=8005) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:51:08.620-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:51:08.621-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:51:08.621-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:51:08.638-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:51:08.664-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:51:08.663-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:51:08.676-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:51:08.676-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:51:08.736-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.122 seconds
[2024-05-01T18:51:39.145-0300] {processor.py:161} INFO - Started process (PID=8130) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:51:39.146-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:51:39.148-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:51:39.148-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:51:39.165-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:51:39.193-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:51:39.193-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:51:39.208-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:51:39.208-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:51:39.291-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.150 seconds
[2024-05-01T18:52:09.454-0300] {processor.py:161} INFO - Started process (PID=8258) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:52:09.455-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:52:09.456-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:52:09.456-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:52:09.476-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:52:09.503-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:52:09.502-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:52:09.516-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:52:09.516-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:52:09.575-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.126 seconds
[2024-05-01T18:52:39.977-0300] {processor.py:161} INFO - Started process (PID=8383) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:52:39.978-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:52:39.980-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:52:39.980-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:52:40.001-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:52:40.030-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:52:40.029-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:52:40.042-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:52:40.042-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:52:40.108-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.137 seconds
[2024-05-01T18:53:10.488-0300] {processor.py:161} INFO - Started process (PID=8510) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:53:10.489-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:53:10.491-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:53:10.491-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:53:10.507-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:53:10.532-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:53:10.532-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:53:10.544-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:53:10.544-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:53:10.602-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.118 seconds
[2024-05-01T18:53:40.788-0300] {processor.py:161} INFO - Started process (PID=8636) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:53:40.789-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:53:40.790-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:53:40.790-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:53:40.807-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:53:40.833-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:53:40.833-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:53:40.846-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:53:40.846-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:53:40.899-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.116 seconds
[2024-05-01T18:54:11.632-0300] {processor.py:161} INFO - Started process (PID=8762) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:54:11.633-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:54:11.635-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:54:11.635-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:54:11.652-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:54:11.678-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:54:11.677-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:54:11.690-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:54:11.690-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:54:11.817-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.189 seconds
[2024-05-01T18:54:42.506-0300] {processor.py:161} INFO - Started process (PID=8890) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:54:42.507-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:54:42.508-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:54:42.508-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:54:42.524-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:54:42.550-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:54:42.550-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:54:42.647-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:54:42.647-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:54:43.204-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.703 seconds
[2024-05-01T18:55:13.861-0300] {processor.py:161} INFO - Started process (PID=9019) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:55:13.862-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py for tasks to queue
[2024-05-01T18:55:13.863-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:55:13.863-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:55:13.879-0300] {processor.py:840} INFO - DAG(s) 'dag_exemplo' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py
[2024-05-01T18:55:13.905-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:55:13.904-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-01T18:55:13.980-0300] {logging_mixin.py:188} INFO - [2024-05-01T18:55:13.980-0300] {dag.py:3954} INFO - Setting next_dagrun for dag_exemplo to None, run_after=None
[2024-05-01T18:55:14.042-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/dag_exemplo.py took 0.185 seconds
